### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by kickasstorrents** [kickasstorrents/KAT#1]
# Project Scope

Develop a working clone of Kick Ass Torrents using [HelloZeroNet/ZeroNet](https://github.com/HelloZeroNet/ZeroNet)

## Tasks

- [ ] Finish initial prototype based off a clone of [ZeroTorrent](http://127.0.0.1:43110/ZeroTorrent.bit/)
- [ ] Refine it so that it can be published
- [ ] Decide on a license (GPL 2/3?)
- [ ] Clean up HTML
  - [ ] Use templating system of some sort to make the HTML more friendly to read and develop, perhaps use [Pug](https://github.com/pugjs/pug)?
- [ ] Clean up JavaScript
  - [ ] Familiarize oneself with the [ZeroFrame API](https://zeronet.readthedocs.io/en/latest/site_development/zeroframe_api_reference/).
  - [ ] Rewrite the JavaScript (How? Perhaps use TypeScript)
  - [ ] Test the JavaScript? Again, How? Is this possible with ZeroNet?
- [ ] Clean up CSS - Right now it's a hodge-podge of copied and pasted CSS from the KAT archives. A complete re-write would be nice if only to understand it and figure out what is and is not needed.
- [ ] Forums?
- [ ] Blogs?
